FROM bellsoft/liberica-runtime-container:jre-24-cds-musl as optimizer
WORKDIR /app
COPY project/target/application.jar app.jar
RUN java -Djarmode=tools -jar /app/app.jar extract --layers --destination extracted

FROM bellsoft/liberica-runtime-container:jre-24-slim-musl

WORKDIR /app
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
COPY --from=optimizer /app/extracted/dependencies/ ./
COPY --from=optimizer /app/extracted/spring-boot-loader/ ./
COPY --from=optimizer /app/extracted/snapshot-dependencies/ ./
COPY --from=optimizer /app/extracted/application/ ./