FROM bellsoft/liberica-runtime-container:jdk-25-musl as builder
WORKDIR /app
ADD . /app/petclinic
RUN cd petclinic && ./mvnw -DskipTests=true clean package

FROM bellsoft/liberica-runtime-container:jre-25-slim-musl as optimizer
WORKDIR /app
COPY --from=builder /app/petclinic/target/spring-petclinic-*.jar app.jar
RUN java -Djarmode=tools -jar /app/app.jar extract --layers --destination extracted

FROM bellsoft/liberica-runtime-container:jre-25-slim-musl

WORKDIR /app
COPY --from=optimizer /app/extracted/dependencies/ ./
COPY --from=optimizer /app/extracted/spring-boot-loader/ ./
COPY --from=optimizer /app/extracted/snapshot-dependencies/ ./
COPY --from=optimizer /app/extracted/application/ ./
EXPOSE 8080

RUN java -Dspring.aot.enabled=true -XX:AOTCacheOutput=app.aot -Dspring.context.exit=onRefresh -jar /app/app.jar
ENTRYPOINT ["java", "-Dspring.aot.enabled=true", "-XX:AOTCache=app.aot", "-jar", "/app/app.jar"]